# docker build --no-cache -f ./Dockerfile-Build --output . .
# Learn about building .NET container images:
# https://github.com/dotnet/dotnet-docker/blob/main/samples/README.md
FROM --platform=$BUILDPLATFORM mcr.microsoft.com/dotnet/sdk:8.0 AS build
ARG TARGETARCH
WORKDIR /source

# Copy source code and publish app
COPY --link ./app .
RUN dotnet publish -c Debug -p:UseAppHost=false -o /publish

RUN apt update -y \
    && apt install -y --no-install-recommends zip \
    && rm -rf /var/lib/apt/lists/*

RUN zip -r /publish.zip /publish

# Output stage
# Learn more about exporting binaries with Docker: https://docs.docker.com/build/building/export/
FROM scratch

COPY --link --from=build /publish.zip .